name: FizzBuzz documentation
projectname: Fizz
markdown: kramdown
highlighter: rouge
baseurl: /fizz               # should be the name of your Github repository
apidocs: /fizz/latest/api    # starts with baseurl
githuburl: https://github.com/denisrosset/fizz
sources: https://github.com/denisrosset/fizz/blob/master/
# logourl: https://pbs.twimg.com/profile_images/3005141692/dc8e1eb36b6cbd2b5726f63c50adf7f2.png # uncomment with a real image
# chatname: Gitter
# chaturl: https://gitter.im/...
# buildname: Travis
# buildurl: https://travis-ci.org/...
collections:
  tut:
    output: true
